
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // ใช้ process.env ตรง ๆ (ไม่ใช่ env() ของ prisma ที่ throw ทันทีถ้าค่าหาย)
    // → `prisma generate` บน Vercel ผ่านแม้ DATABASE_URL ยังไม่ถูก inject
    // ส่วน migrate/runtime ยังอ่านค่าจริงจาก env ตอน connect
    url: process.env.DATABASE_URL ?? "",
  },
});
